### ISSUE TITLE
Problems running example/exp_ovsg_llm.py

### ISSUE THREAD

**Issue by percypeng5221** [changhaonan/OVSG#2]
Hi Haonan,

Great work! I followed all the instructions until: `python example/exp_ovsg_llm.py`. But after running this command, I received this error:
```
/home/percy/princeton/OVSG/example/exp_ovsg_llm.py:20: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="../ovsg/config", config_name="config")
/home/percy/miniforge3/envs/ovsg/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/percy/miniforge3/envs/ovsg/lib/python3.10/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
/home/percy/princeton/OVSG/ovsg/utils/spatial/spatial_encoder.py:319: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(
Spatial encoder loaded from data/spatial_encoder
[ WARN:0@6.997] global loadsave.cpp:241 findDecoder imread_('/home/percy/princeton/OVSG/ovsg/data/notion/user.jpeg'): can't open/read file: check file path/integrity
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/percy/princeton/OVSG/example/exp_ovsg_llm.py", line 34, in launch_ovsg_llm
    app.eval(task_name_list[0], hitl=True, query_method=query_method, enable_render=enable_render)
  File "/home/percy/princeton/OVSG/ovsg/app.py", line 195, in eval
    reply, done = self.env.eval(task_name, **kwargs)
  File "/home/percy/princeton/OVSG/ovsg/env/notionovidb.py", line 1035, in eval
    task_type, task_scene = task_name.split(":")
ValueError: not enough values to unpack (expected 2, got 1)

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
I've modified my openai.yaml and changed the name of the file as instructed like this:
```
# @package _global_
gpt_model: "gpt-4o"
api_key:
  {
    "gpt-3.5-turbo-0301": "my key",
    "gpt-4o": "my key",
  }
```
Could you give me a hand? 
Thanks!
Percy

**Comment by Kowndinya2000** [comment]
Hi Percy Peng,
In `config.yaml`, make sure the `task_name` is of the format `gen_query:room1` or `eval_query:room1` or `gen_n_eval_query:room1`, which specifies both the task_type and scene_name split by `:`. Here `room1` is one of the scenes in `DOVE-G` dataset. For more, you may look at `README.md` in the `evaluation` folder.
